controlhub/experiment/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, IntegerField
from wtforms.validators import DataRequired, Length, Regexp, Optional, NumberRange


class SubmissionForm(FlaskForm):
    mfile1 = TextAreaField('mfile1', [
        DataRequired(),
        Regexp('^C_init=\[(.)*\]; *%*(.)*\sO_init=\[(.)*\]; *%*(.)*$', message=("Initialization is not correct, it must contain just 2 lines!"))],
        default='C_init=[0]; %Initialization of the controller internal state \nO_init=[0;0]; %Initialization of the observer internal state',
        id="ReadResult1")

    mfile2 = TextAreaField('mfile2', [
        DataRequired(),
        Regexp('^[\S\s]*$', message=("Controller is not correct!"))],
        default='function [u, C_out]=control(t, x,  x_ref, C_in)\n\
%-------------------------------------------------------------------------------------------\n\
%t - time\n\
%x=(theta,alpha,d_theta,d_alpha) is the system state (estimated by the observer),\n\
%where the angle alpha=0 corresponds to the lower position of the pendulum.\n\
%the variable C_in(out) is the internal variable of the controller (e.g. to realize integrator).\n\
%C_in corresponds to C_out at the previous instant of time.\n\
%The command C_out=C_in has to be included if the controller does not need an internal state.\n\
%-------------------------------------------------------------------------------------------\n\
%The following change of coordinate makes the state x(2)=0 corresponding to the upper\n\
%position of the pendulum.\n\
x(2)=mod (x(2),2*pi)-pi;\n\
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\
% THE USER-DEFINED CONTROLLER HAS TO BE REALIZED BELOW\n\
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\
C_out=C_in;\n\
%The static linear feedback u=K(x-x^ref) stabilizes the pendulum in the upper position\n\
%and tracks the reference theta^ref(t)=0.3sin(t).\n\
u=[2 -35 1.5 -3]*(x-x_ref);',
        id="ReadResult2")

    mfile3 = TextAreaField('mfile3', [
        DataRequired(),
        Regexp('^[\S\s]*$', message=("Observer is not correct!"))],
        default='function [x, O_out]=observer(t, y, u, O_in) \n\
%----------------------------------------------------------------------------------------- \n\
%t - time \n\
%y = (theta, alpha) - sensor output \n\
%u - the control input\n\
%x=(theta,alpha,d_theta,d_alpha) - the state estimate\n\
%O  is an internal variable observer (e.g. to realize a transfer function).\n\
%O_in corresponds to O_out in the previous instant of time, i.e. O_in=O(i-1) but O_out=O(i).\n\
%The command O_out=O_in has to be utilized if the observer does not need an internal state.\n\
%------------------------------------------------------------------------------------------\n\
%The observer given below estimates the time derivative of y as follows\n\
%  dy ~= W(s)y,\n\
% where  W(s)=(50s)/(s+50).\n\
% The algorithm is realized using implicit Euler discretization in two steps.\n\
%1) the update of the observer internal state:\n\
O_out=(0.0020*50*y+O_in)/(1+50*0.0020); % 0.0020 is the sampling period of the system\n\
%2) the estimate of the state:\n\
x=[y; 50*(y-O_out)];',
        id="ReadResult3")

    username = StringField('username', [
        DataRequired(),
        Length(min=3, max=10, message=('Username size must be in the interval [4, 10]')),
        Regexp('^[\w]+$', message=("Don't use any symbols different from Aa-Zz, _, 0-9"))], default="NaN")

    mult_run = IntegerField('mult_run', [
        Optional(),
        NumberRange(min=1, max=10)], default=1)
    submit = SubmitField('Submit')

controlhub/experiment/routes.py
from flask import url_for, render_template, session, request, redirect, flash, Blueprint
from flask import current_app
from datetime import datetime as dt
from controlhub.models import Submissions
from controlhub.experiment.forms import SubmissionForm
from controlhub import db
import os
import re

experiment = Blueprint('experiment', __name__)


@experiment.route('/exp_start')
def exp_start():
    return render_template('exp_start.html', title='experiment')


@experiment.route('/matlab')
def matlab():
    subm_address = current_app.config['SUBMISSION_ADDRESS']
    subm_folder = session['username'] + '!' + dt.now().strftime("%Y-%m-%d-%H-%M-%S")

    oldmask = os.umask(000)
    os.mkdir(subm_address + subm_folder, 0o777)
    os.umask(oldmask)

    with open(subm_address + subm_folder + '/' + 'init.m', 'wb+') as f1:
        f1.write(session['init'])
    with open(subm_address + subm_folder + '/' + 'control.m', 'wb+') as f2:
        f2.write(session['control'])
    with open(subm_address + subm_folder + '/' + 'observer.m', 'wb+') as f3:
        f3.write(session['observer'])

    # Create an instance of the Submission class
    print(session['exp_type'])
    submission_data = Submissions(folder=subm_folder, exp_type=session['exp_type'])
    db.session.add(submission_data)  # Adds new record to database
    db.session.commit()  # Commits all changes
    return redirect(url_for('video.video_page'))


@experiment.route('/exp_start/experiments', methods=["GET", "POST"])
def experiments():
    exp_type = request.args.get('exp_type')
    form = SubmissionForm()
    if form.is_submitted():
        print("submitted")
    if form.validate():
        print("valid")

    print(form.errors)

    if submit_limit():
        print('Submit limit is reached!')
        flash('Submit limit is reached for now, please wait!')
    else:
        print('Submit limit is not reached')
        if form.validate_on_submit():
            print("Validated!!!")
            if request.method == "POST":
                session['username'] = request.form["username"]
                session['init'] = bytes(request.form["mfile1"], encoding='utf-8')
                session['control'] = bytes(request.form["mfile2"], encoding='utf-8')
                session['observer'] = bytes(request.form["mfile3"], encoding='utf-8')
                session['exp_type'] = exp_type
                #session['exp_num'] = bytes(request.form["mult_run"], encoding='utf-8')
            return redirect(url_for('experiment.matlab'))
        else:
            print("Not validated!")
    return render_template('experiments.html', form=form, exp_type=exp_type, title='experiment')


def listdir_nohidden(path):
    files = os.listdir(path)
    return [i for i in files if not re.match('^\.', i)]


def submit_limit():
    files = listdir_nohidden(current_app.config['SUBMISSION_ADDRESS'])
    if len(files) > 10:
        return True
    return False

controlhub/main/routes.py
from flask import render_template, Blueprint

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    return render_template('home.html')


@main.route('/tech_data')
def tech_data():
    return render_template('tech_data.html')


@main.route('/about')
def about():
    return render_template('about.html')

controlhub/tables/routes.py
from flask import render_template, session, request, Blueprint
from .forms import COLUMNS, COLS_DEF, TableForm
from controlhub.models import Control_quality

table = Blueprint('table', __name__)


@table.route('/results')
def results():
    #cols = {}
    session['cols'] = {}
    session['rows_num'] = 10
    session['submname'] = ''
    #session['sort_col'] = ''
    #session['sort_dir'] = ''
    for key in COLUMNS:
        if key not in COLS_DEF:
            session['cols'][key] = "n"
        else:
            session['cols'][key] = "y"
    return render_template('results.html', title='results')


@table.route('/results/tables', methods=["GET", "POST"])
def tables():
    page = request.args.get('page', 1, type=int)
    exp_type = request.args.get('exp_type')
    sort_col = request.args.get('sort_col', 'id')
    print('sort_col = ', sort_col)
    sort_dir = request.args.get('sort_dir', 'desc')
    print('sort_dir = ', sort_dir)
    form = TableForm()

    if form.validate_on_submit():
        print('Validated!')
        if request.method == "POST":
            #session['rows_num'] = int(request.form["rows_limit"])
            for key in session['cols']:
                if request.form.get(key, False) == 'y':
                    session['cols'][key] = 'y'
                elif not request.form.get(key, False):
                    session['cols'][key] = 'n'
            username = request.form.get('username', False)
            if not username:
                session['submname'] = ''
            if username:
                session['submname'] = username
            data = Control_quality.query.filter_by(exp_type=exp_type).filter(
                    Control_quality.username.op('regexp')(r'({})+'.format(username))).order_by(
                    getattr(getattr(Control_quality, sort_col), sort_dir)()).paginate(page=page, per_page=session['rows_num'])
            return render_template('tables.html', form=form, exp_type=exp_type, sort_col=sort_col, sort_dir=sort_dir, data=data, columns=COLUMNS, cols_show=session['cols'], _anchor='table', title='table', submname=session['submname'])
    else:
        print("Not validated!")
    data = Control_quality.query.filter_by(exp_type=exp_type).filter(
        Control_quality.username.op('regexp')(r'({})+'.format(session['submname']))).order_by(
        getattr(getattr(Control_quality, sort_col), sort_dir)()).paginate(page=page, per_page=session['rows_num'])
    return render_template('tables.html', form=form, exp_type=exp_type, sort_col=sort_col, sort_dir=sort_dir, data=data, columns=COLUMNS, cols_show=session['cols'], _anchor="table", title='table', submname=session['submname'])


@table.route('/item/<int:id>')
def flask_link(id):
    element = Control_quality.query.get(id)
    print(element)
    link = "/static/exp_results/" + element.folder + ".zip"
    return render_template('download_page.html', Date=element.date, Username=element.username, Link=link, title='download')

controlhub/video/routes.py
from flask import render_template, Response, Blueprint
from flask import current_app
from controlhub.models import Submissions
from controlhub.camera_opencv import Camera

video = Blueprint('video', __name__)


@video.route('/video_page')
def video_page():
    """Video streaming home page."""
    resultset = Submissions.query
    return render_template('video_body.html', submissions=resultset[-8:], title='video')


def gen(camera, timer_directory):
    """Video streaming generator function."""
    while True:
        with open(timer_directory) as f:
            text_var = f.read()
        camera.impose_text(text_var)
        frame = camera.get_frame()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')


@video.route('/video_feed')
def video_feed():
    """Video streaming route. Put this in the src attribute of an img tag."""
    return Response(gen(Camera(), current_app.config['TIMER_DIR']),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

controlhub/templates/about.html
{% extends 'layout.html' %}
{% block content %}
	<div class="content-section" style="margin-top:100px;">
			<p><strong>Contact info:</strong></p>
			<ul class="list-unstyled">
				<br>
				<li>Project engineer: fiodar.hancharou@inria.fr</li>
				<br>
				<li>Project coordinator: andrey.polyakov@inria.fr</li>
				<br>
				<li><a href="http://controlhub.gforge.inria.fr/">ControlHub project</a></li>
			</ul>
	</div>
{% endblock %}

controlhub/templates/download_page.html
{% extends 'layout.html' %}

{% block content %}
	<div class="content-section" style="margin-top:100px;">
		<div class="row justify-content-md-center">
			<div class="scheme">
				<h1>The submission was made at {{Date}} and its owner is {{Username}}</h1><a href= {{Link}}><hr><small>Click here to download</small> </a>
			</div>
		</div>
    </div>
	<style>
	.scheme {
        float: center;
        width: 750px;
	}
	.scheme a {
		display: block;
		float: center;
		background-color: #8cbbd3;
		color: #ffffff;
		font-size: 24px;
		font-weight: 300;
		text-align: center;
		text-decoration: none;
		padding:11px 51px;
	}
	</style>
{% endblock %}

controlhub/templates/exp_start.html
{% extends 'layout.html' %}
{% block content %}
    <div class="content-section" style="margin-top:100px;">
        <div class="row justify-content-md-center">
            <h3>Please, choose the task type:</h3>
        </div>
        <div class="row justify-content-md-center mt-3">
            <div class="btn-group btn-group-lg" role="group" aria-label="Basic outlined example">
                {% if exp_type == 'stabilisation' %}
                    <a href={{ url_for('experiment.experiments', exp_type='stabilisation') }} class="btn btn-primary ">Stabilisation</a>
                    <a href={{ url_for('experiment.experiments', exp_type='step_signal') }} class="btn btn-outline-primary">Step signal</a>
                    <a href={{ url_for('experiment.experiments', exp_type='ref_trajectory') }} class="btn btn-outline-primary">Continuous trajectory</a>
                {% elif exp_type == 'step_signal' %}
                    <a href={{ url_for('experiment.experiments', exp_type='stabilisation') }} class="btn btn-outline-primary">Stabilisation</a>
                    <a href={{ url_for('experiment.experiments', exp_type='step_signal') }} class="btn btn-primary">Step signal</a>
                    <a href={{ url_for('experiment.experiments', exp_type='ref_trajectory') }} class="btn btn-outline-primary">Continuous trajectory</a>
                {% elif exp_type == 'ref_trajectory' %}
                    <a href={{ url_for('experiment.experiments', exp_type='stabilisation') }} class="btn btn-outline-primary">Stabilisation</a>
                    <a href={{ url_for('experiment.experiments', exp_type='step_signal') }} class="btn btn-outline-primary">Step signal</a>
                    <a href={{ url_for('experiment.experiments', exp_type='ref_trajectory') }} class="btn btn-primary">Continuous trajectory</a>
                {% else %}
                    <a href={{ url_for('experiment.experiments', exp_type='stabilisation') }} class="btn btn-outline-primary">Stabilisation</a>
                    <a href={{ url_for('experiment.experiments', exp_type='step_signal') }} class="btn btn-outline-primary">Step signal</a>
                    <a href={{ url_for('experiment.experiments', exp_type='ref_trajectory') }} class="btn btn-outline-primary">Continuous trajectory</a>
                {% endif %}
            </div>
        </div>
        {% include 'how_to.html' %}
    </div>
{% endblock %}

controlhub/templates/how_to.html
<div class="row justify-content-md-center mt-5">
    <div class="col-md-auto">
        <h3 class="text-center">How to make experiment</h3>
    </div>
</div>

<div class="row justify-content-md-center mt-3" style="background-image: url(../static/img/background_how_to.jpg)">
    <div class="col-md-auto">
        <a class="btn btn-primary" href={{ url_for('main.tech_data') }}>Download<br>simulator</a>
    </div>
    <div class="col-md-auto align-self-center">
        <img src="/static/img/arrow.jpg" style="width:30px;height:30px;">
    </div>
    <div class="col-md-auto">
        <a class="btn btn-primary" href={{ url_for('main.tech_data') }}>Develop<br>solution</a>
    </div>
    <div class="col-md-auto align-self-center">
        <img src="/static/img/arrow.jpg" style="width:30px;height:30px;">
    </div>
    <div class="col-md-auto">
        <a class="btn btn-primary" href={{ url_for('experiment.exp_start') }}>Submit<br>solution</a>
    </div>
    <div class="col-md-auto align-self-center">
        <img src="/static/img/arrow.jpg" style="width:30px;height:30px;">
    </div>
    <div class="col-md-auto">
        <a class="btn btn-primary" href={{ url_for('table.results') }}>Check<br> the result</a>
    </div>
</div>

controlhub/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

	{% if title %}
		<title>ControlHub - {{ title }}</title>
	{% else %}
		<title>ControlHub</title>
	{% endif %}
</head>
<body>
	<header class="site-header">
		<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
			<div class="container">
				<a class="navbar-brand mr-4" href="/">
					<img alt="Qries" src="/static/img/ControlHub_gr2.jpg">
				</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarToggle">
					<div class="navbar-nav mr-auto">
						<!-- Navbar Left Side -->
						<a class="nav-item nav-link" href={{ url_for('main.home') }}>Home</a>
						<a class="nav-item nav-link" href={{ url_for('main.tech_data') }}>Downloads</a>
						<a class="nav-item nav-link"href={{ url_for('experiment.exp_start') }}>Make an experiment</a>
						<a class="nav-item nav-link"href={{ url_for('video.video_page') }}>Show room</a>
						<a class="nav-item nav-link"href={{ url_for('table.results') }}>Table of results</a>
						<a class="nav-item nav-link" href={{ url_for('main.about') }}>About</a>
					</div>
					<!-- Navbar Right Side -->
					<div class="navbar-nav">
						<a class="nav-item nav-link" href="https://inria.fr/fr">
							<img alt="Qries" src="/static/img/Inria_gr2.jpg">
						</a>
					</div>
				</div>
			</div>
		</nav>
	</header>
	<main role="main" class="container" style="max-width:100%;">
		{% block content %}{% endblock %}
	</main>
	<!--
	{% include 'footer.html' %}
	-->
	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->

	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

controlhub/templates/tables.html
{% extends 'layout.html' %}
{% block content %}
	<script type="text/x-mathjax-config">
		MathJax.Hub.Config({
		  TeX: {
			 equationNumbers: {  autoNumber: "AMS"  },
			 extensions: ["AMSmath.js", "AMSsymbols.js", "autobold.js", "color.js"]
		  }
		});
	</script>
	<script type="text/javascript"
		src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
	</script>

    <div class="content-section" style="margin-top:100px;">
        <div class="row justify-content-md-center">
            <h3>Please, choose the task type you want to see the results for:</h3>
        </div>

        <div class="row justify-content-md-center">
            <div class="btn-group btn-group-lg" role="group" aria-label="Basic outlined example">
                {% if exp_type == 'stabilisation' %}
                    <a href="{{ url_for('table.tables', exp_type='stabilisation') }}" class="btn btn-primary">Stabilisation</a>
                    <a href="{{ url_for('table.tables', exp_type='step_signal') }}" class="btn btn-outline-primary">Step signal</a>
                    <a href="{{ url_for('table.tables', exp_type='ref_trajectory') }}" class="btn btn-outline-primary">Continuous trajectory</a>
                {% elif exp_type == 'step_signal' %}
                    <a href="{{ url_for('table.tables', exp_type='stabilisation') }}" class="btn btn-outline-primary">Stabilisation</a>
                    <a href="{{ url_for('table.tables', exp_type='step_signal') }}" class="btn btn-primary">Step signal</a>
                    <a href="{{ url_for('table.tables', exp_type='ref_trajectory') }}" class="btn btn-outline-primary">Continuous trajectory</a>
                {% elif exp_type == 'ref_trajectory' %}
                    <a href="{{ url_for('table.tables', exp_type='stabilisation') }}" class="btn btn-outline-primary">Stabilisation</a>
                    <a href="{{ url_for('table.tables', exp_type='step_signal') }}" class="btn btn-outline-primary">Step signal</a>
                    <a href="{{ url_for('table.tables', exp_type='ref_trajectory') }}" class="btn btn-primary">Continuous trajectory</a>
                {% else %}
                    <a href="{{ url_for('table.tables', exp_type='stabilisation') }}" class="btn btn-outline-primary">Stabilisation</a>
                    <a href="{{ url_for('table.tables', exp_type='step_signal') }}" class="btn btn-outline-primary">Step signal</a>
                    <a href="{{ url_for('table.tables', exp_type='ref_trajectory') }}" class="btn btn-outline-primary">Continuous trajectory</a>
                {% endif %}
            </div>
        </div>
		<div class="row justify-content-md-center mt-2">
			  <a class="btn btn-primary" data-toggle="collapse" href="#collapseInfo" role="button" aria-expanded="false" aria-controls="collapseExample">
				  Additional information
			  </a>
			<div class="collapse" id="collapseInfo">
				<div class="card card-body">
					<h1 style="font-size:20px;margin-top:0px;margin-bottom:0px;">The following table summarises the perfomance of submitted controller according to the following criteria:</h1>
					<h1 style="font-size:20px;margin-top:0px;margin-bottom:0px;"> \(||e_{q}||_{L^2} = ||q - q_{ref}||_{L^2}\) and \(||e_{q}||_{L^\infty} = ||q - q_{ref}||_{L^\infty}\) </h1>
					<h1 style="font-size:20px;margin-top:0px;margin-bottom:0px;"> where \(e_q\) is an error, \(q \in [\theta, \alpha, \theta', \alpha']\), and \(L^{2}, L^\infty\) norms are computed on the time interval [3, 20] sec </h1>
				</div>
			</div>
		</div>
    </div>
	<!--
	{% for key in cols_show %}
		<input type="checkbox" id="{{ key }}" name="{{ key }}" value="y">
		<label for="{{ key }}">{{ columns[key] }}</label>
	{% endfor %}
	-->
	<div class="content-section">
		<form id="tableform" method="POST" action="{{ url_for('table.tables', exp_type=exp_type) }}">
			{{ form.csrf_token }}
			<br>
			<div class="row justify-content-md-center mt-2">
				<a class="btn btn-primary" data-toggle="collapse" href="#collapseCols" role="button" aria-expanded="false" aria-controls="collapseExample">
					  Hide/show columns
				</a>
				<div class="collapse mt-2" id="collapseCols">
					{% for i in cols_show %}
						{% if cols_show[i] == 'y' %}
							{{ form[i](checked="checked") }}
							<label for="{{ i }}">{{ columns[i] }}</label>
						{% else %}
							{{ form[i](unchecked="unchecked") }}
							<label for="{{ i }}">{{ columns[i] }}</label>
						{% endif %}
					{% endfor %}
				</div>
			</div>
			<p>Search by the submission name:</p>
			{{ form.username(onchange="submit()", value=submname) }}
			{% if form.username.errors %}
				<ul class="errors">
					{% for error in form.username.errors %}
						<li>{{ error }}</li>
					{% endfor %}
				</ul>
			{% endif %}
			{{ form.submit(class="btn btn-outline-info") }}
		</form>
	</div>
	<div class="table-section">
		<div class="table-wrapper">
			<div class="table-scroll">
					<table id="control_quality">
						<thead>
							<tr>
								{% if sort_col == 'id' %}
									<th>ID ↓</th>
								{% else %}
									<th>ID </th>
								{% endif %}
								<th>Submission name</th>
								<th>Date</th>
								<th>Results</th>
								{% for i in cols_show %}
									{% if cols_show[i]=='y' %}
										{% if i == sort_col %}
											<th><a href="{{ url_for('table.tables', exp_type=exp_type, sort_col=i, sort_dir='asc') }}" class="btn btn-primary">{{ columns[i] }} ↑</a></th>
										{% else %}
											<th><a href="{{ url_for('table.tables', exp_type=exp_type, sort_col=i, sort_dir='asc') }}" class="btn btn-outline-primary">{{ columns[i] }}</a></th>
										{% endif %}
									{% endif %}
								{% endfor %}
							<tr>
						</thead>

						<tbody>
							{% for i in data.items %}
								<tr>
									<td>{{ i.id }}</td>
									<td>{{ i.username }}</td>
									<td>{{ i.date }}</td>
									<td><a href="{{ url_for('table.flask_link', page=data.page, id=i.id) }}">Link</a></td>
									{% for j in cols_show %}
										{% if cols_show[j]=='y'%}
											<td>{{ i[j] }}</td>
										{% endif %}
									{% endfor %}
								</tr>
							{% endfor %}
						</tbody>
					</table>
			</div>
		</div>

		{% for page_num in data.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
			{% if page_num %}
				{% if data.page == page_num %}
					<a class="btn btn-info my-3" href="{{ url_for('table.tables', exp_type=exp_type, sort_col=sort_col, sort_dir=sort_dir, page=page_num) }}">{{ page_num }}</a>
				{% else %}
					<a class="btn btn-outline-info my-3" href="{{ url_for('table.tables', exp_type=exp_type, sort_col=sort_col, sort_dir=sort_dir, page=page_num) }}">{{ page_num }}</a>
				{% endif %}
			{% else %}
			...
			{% endif %}
		{% endfor %}
	</div>
	<style>
    .table-wrapper {
    	position:relative;
	}

	.table-scroll {
	  overflow:auto;
	  margin-top:20px;
	}

	#control_quality {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
	}

	#control_quality td, th {
        border: 1px solid #ddd;
        padding: 8px;
	}

	#control_quality tr:nth-child(even) {
        background-color: #f2f2f2;
	}

	#control_quality tr:hover {
	    background-color: #ddd;
	}

	#control_quality th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #5f788a;
        color: white;
	}
	#control_quality th a {
        color: white;
	}
    </style>
{% endblock %}

controlhub/templates/video_body.html
{% extends 'layout.html' %}
{% block content %}
	<div class="content-section" style="margin-top:100px;">
		<div class="row justify-content-md-center">
			<h5>Experiment takes 2-3 minutes. The solution is tested initially on a simulator,</h5>
			<h5>next it is validated on the real experimental setup. The camera installed in the lab</h5>
			<h5>allows the user to survey the experiment. The results of the experiment can be found <a href={{ url_for('table.results') }}>here</a></h5>
		</div>
	</div>
	<div class="row">
		<div class="col-md-9">
			<div class="content-section">
				<div class="row justify-content-md-center">
					<h3 class="text-center">Online video</h3>
				</div>
				<div class="row justify-content-md-center" style="margin-top:66px;">
					<img src={{ url_for('video.video_feed') }}>
				</div>
			</div>
		</div>
		<div class="col-md-3">
			<div class="content-section">
				<div class="row justify-content-md-center">
					<h3 class="text-center">Recent submissions</h3>
				</div>
				<div class="row justify-content-md-center">
					{% for submission in submissions %}
						<ul id="submission">
							<li><span class="field-value">{{ submission.folder }}</span>							</li>
							<br>
						</ul>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}